name: Deploy Images to GHCR when pushing to main branch

on:
  push:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Building images if the remote version has changed
        run: |
          echo "Triggering Docker Build"  
          echo "Building AMD64 image"  
          docker buildx build --platform linux/amd64 -t ghcr.io/multipixelone/plexamp:amd64 --load .
          docker push ghcr.io/multipixelone/plexamp:amd64
          docker buildx build --platform linux/amd64 -t ghcr.io/multipixelone/plexamp:amd64-${CURRENT_VERSION} --load .
          docker push ghcr.io/multipixelone/plexamp:amd64-${CURRENT_VERSION}
